name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          always-auth: false
          node-version: ">=12.x"
      - name: Build application
        run: npm build
